#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$HOME/.profile"

# Fetch the latest origin/master to accurately determine the set of changed
# files on this branch.
echo "Running git fetch..."
git fetch
echo "Running git fetch... done"

echo "install asdf plugins"
asdf install
echo "done installing"

# Link the trace-script so we can have pretty steps in the buildkite ui
ln -s "$(pwd)/enterprise/dev/ci/scripts/trace-command.sh" tr 2>/dev/null || true

# Force yarn to use our caching proxy for node dependencies 
sed -i -e "s#https://registry.npmjs.org/#http://verdaccio-proxy/#g" yarn.lock
